# #
# # COPYRIGHT Ericsson 2024
# #
# #
# #
# # The copyright to the computer program(s) herein is the property of
# #
# # Ericsson Inc. The programs may be used and/or copied only with written
# #
# # permission from Ericsson Inc. or in accordance with the terms and
# #
# # conditions stipulated in the agreement/contract under which the
# #
# # program(s) have been supplied.
# #
# # Details of this file can be found in docs/service-accounts.md
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-service-assurance.name" . }}-gas-patcher-sa
  labels:
    {{- include "eric-service-assurance.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-service-assurance.helm-annotations" .| nindent 4 }}
